var city = [{
    title: "热门城市",
    type: 'hot',
    item: [{
        "name": "南宁吴圩机场",
        "key": "热门",
        "test": "testValue",
        "code": "NNG"
      },
      {
        "name": "上海虹桥机场",
        "key": "热门",
        "code": "SHA"
      }, {
        "name": "广州白云机场",
        "key": "热门",
        "code": "CAN"
      }, {
        "name": "北京首都机场",
        "key": "热门",
        "code": "PEK"
      }, {
        "name": "深圳宝安机场",
        "key": "热门",
        "code": "SZX"
      }, {
        "name": "成都双流机场",
        "key": "热门",
        "code": "CTU"
      }, {
        "name": "重庆江北机场",
        "key": "热门",
        "code": "CKG"
      }, {
        "name": "上海浦东机场",
        "key": "热门",
        "code": "PVG"
      }, {
        "name": "昆明巫家坝机场",
        "key": "热门",
        "code": "KMG"
      }, {
        "name": "西安咸阳机场",
        "key": "热门",
        "code": "XIY"
      },
    ]
  },
  {
    title: "A",
    item: [{
      "name": "阿克苏机场",
      "key": "A",
      "code": "AKU"
    }, {
      "name": "安庆(天柱山）机场",
      "key": "A",
      "code": "AQG"
    }, {
      "name": "安阳北郊机场",
      "key": "A",
      "code": "AYN"
    }, {
      "name": "安康机场",
      "key": "A",
      "code": "AKA"
    }, {
      "name": "鞍山机场",
      "key": "A",
      "code": "AOG"
    }, {
      "name": "阿勒泰机场",
      "key": "A",
      "code": "AAT"
    }, ]
  },
  {
    title: "B",
    item: [{
      "name": "北京南苑机场",
      "key": "B",
      "code": "NAY"
    }, {
      "name": "包头二里半机场",
      "key": "B",
      "code": "BAV"
    }, {
      "name": "北海福城机场",
      "key": "B",
      "code": "BHY"
    }, {
      "name": "昌都邦达",
      "key": "B",
      "code": "BDU"
    }, {
      "name": "保山云瑞机场",
      "key": "B",
      "code": "BSD"
    }, {
      "name": "蚌埠机场",
      "key": "B",
      "code": "BFU"
    }, ]
  },
  {
    title: "C",
    item: [{
      "name": "长沙黄花机场",
      "key": "C",
      "code": "CSX"
    }, {
      "name": "长春龙嘉国际机场",
      "key": "C",
      "code": "CGQ"
    }, {
      "name": "常州奔牛机场",
      "key": "C",
      "code": "CZX"
    }, {
      "name": "常德桃花源(斗姆湖)机场",
      "key": "C",
      "code": "CGD"
    }, {
      "name": "赤峰玉龙机场",
      "key": "C",
      "code": "CIF"
    }, {
      "name": "重庆万州五桥机场",
      "key": "C",
      "code": "WXN"
    }, {
      "name": "长治王村机场",
      "key": "C",
      "code": "CIH"
    }, {
      "name": "辽宁朝阳机场",
      "key": "C",
      "code": "CHG"
    }, {
      "name": "西藏昌都邦达机场",
      "key": "C",
      "code": "BPX"
    }, ]
  },
  {
    title: "D",
    item: [{
      "name": "大连国际机场",
      "key": "D",
      "code": "DLC"
    }, {
      "name": "丹东浪头机场",
      "key": "D",
      "code": "DDG"
    }, {
      "name": "山西大同机场",
      "key": "D",
      "code": "DAT"
    }, {
      "name": "大理荒草坝机场",
      "key": "D",
      "code": "DLU"
    }, {
      "name": "达州(河市)机场",
      "key": "D",
      "code": "DAX"
    }, {
      "name": "敦煌机场",
      "key": "D",
      "code": "DNH"
    }, {
      "name": "迪庆香格里拉机场",
      "key": "D",
      "code": "DIG"
    }, {
      "name": "长海（大长山岛）机场",
      "key": "D",
      "code": "CNI"
    }, ]
  },
  {
    title: "E",
    item: [{
      "name": "恩施机场",
      "key": "E",
      "code": "ENH"
    }, ]
  },
  {
    title: "F",
    item: [{
      "name": "福州长乐机场",
      "key": "F",
      "code": "FOC"
    }, {
      "name": "阜阳西关机场",
      "key": "F",
      "code": "FUG"
    }, {
      "name": "富蕴机场",
      "key": "F",
      "code": "FYN"
    }, ]
  },
  {
    title: "G",
    item: [{
      "name": "贵阳龙洞堡机场",
      "key": "G",
      "code": "KWE"
    }, {
      "name": "高雄机场",
      "key": "G",
      "code": "KHH"
    }, {
      "name": "桂林两江机场",
      "key": "G",
      "code": "KWL"
    }, {
      "name": "赣州黄金机场",
      "key": "G",
      "code": "KOW"
    }, {
      "name": "格尔木机场",
      "key": "G",
      "code": "GOQ"
    }, {
      "name": "广汉机场",
      "key": "G",
      "code": "GHN"
    }, {
      "name": "格林艾兰",
      "key": "G",
      "code": "GNI"
    }, ]
  },
  {
    title: "H",
    item: [{
      "name": "哈尔滨太平机场",
      "key": "H",
      "code": "HRB"
    }, {
      "name": "杭州萧山机场",
      "key": "H",
      "code": "HGH"
    }, {
      "name": "海口美兰机场",
      "key": "H",
      "code": "HAK"
    }, {
      "name": "合肥骆岗机场",
      "key": "H",
      "code": "HFE"
    }, {
      "name": "呼和浩特白塔国际机场",
      "key": "H",
      "code": "HET"
    }, {
      "name": "内蒙古海拉尔东山机场",
      "key": "H",
      "code": "HLD"
    }, {
      "name": "哈密机场",
      "key": "H",
      "code": "HMI"
    }, {
      "name": "黄山屯溪机场",
      "key": "H",
      "code": "TXN"
    }, {
      "name": "怀化芷江机场",
      "key": "H",
      "code": "HJJ"
    }, {
      "name": "衡阳东江机场",
      "key": "H",
      "code": "HNY"
    }, {
      "name": "汉中西关机场",
      "key": "H",
      "code": "HZG"
    }, {
      "name": "花莲机场",
      "key": "H",
      "code": "HUN"
    }, {
      "name": "和田机场",
      "key": "H",
      "code": "HTN"
    }, {
      "name": "黑河机场",
      "key": "H",
      "code": "HEK"
    }, {
      "name": "兴城机场",
      "key": "H",
      "code": "XEN"
    }, {
      "name": "嫩江机场",
      "key": "H",
      "code": "NNN"
    }, {
      "name": "花莲",
      "key": "H",
      "code": "HLN"
    }, ]
  },
  {
    title: "J",
    item: [{
      "name": "济南遥墙机场",
      "key": "J",
      "code": "TNA"
    }, {
      "name": "佳木斯机场",
      "key": "J",
      "code": "JMU"
    }, {
      "name": "景洪(西双版纳)机场",
      "key": "J",
      "code": "JHG"
    }, {
      "name": "锦州小岭子机场",
      "key": "J",
      "code": "JNZ"
    }, {
      "name": "吉林二台子机场",
      "key": "J",
      "code": "JIL"
    }, {
      "name": "揭阳潮汕机场",
      "key": "J",
      "code": "SWA"
    }, {
      "name": "嘉峪关机场",
      "key": "J",
      "code": "JGN"
    }, {
      "name": "九江庐山机场",
      "key": "J",
      "code": "JIU"
    }, {
      "name": "景德镇罗家机场",
      "key": "J",
      "code": "JDZ"
    }, {
      "name": "尚义机场",
      "key": "J",
      "code": "KNH"
    }, {
      "name": "济宁机场",
      "key": "J",
      "code": "JNG"
    }, {
      "name": "吉安机场",
      "key": "J",
      "code": "KNC"
    }, {
      "name": "九寨沟黄龙(九黄）机场",
      "key": "J",
      "code": "JZH"
    }, {
      "name": "酒泉机场",
      "key": "J",
      "code": "CHW"
    }, {
      "name": "嘉义机场",
      "key": "J",
      "code": "CYI"
    }, ]
  },
  {
    title: "K",
    item: [{
      "name": "喀什机场",
      "key": "K",
      "code": "KHG"
    }, {
      "name": "库尔勒机场",
      "key": "K",
      "code": "KRL"
    }, {
      "name": "克拉玛依机场",
      "key": "K",
      "code": "KRY"
    }, {
      "name": "库车机场",
      "key": "K",
      "code": "KCA"
    }, ]
  },
  {
    title: "L",
    item: [{
      "name": "兰州机场",
      "key": "L",
      "code": "LHW"
    }, {
      "name": "拉萨贡嘎机场",
      "key": "L",
      "code": "LXA"
    }, {
      "name": "柳州白莲机场",
      "key": "L",
      "code": "LZH"
    }, {
      "name": "临沂沭埠岭机场",
      "key": "L",
      "code": "LYI"
    }, {
      "name": "丽江三义机场",
      "key": "L",
      "code": "LJG"
    }, {
      "name": "洛阳机场",
      "key": "L",
      "code": "LYA"
    }, {
      "name": "连云港白塔埠机场",
      "key": "L",
      "code": "LYG"
    }, {
      "name": "泸州蓝田机场",
      "key": "L",
      "code": "LZO"
    }, {
      "name": "临沧机场",
      "key": "L",
      "code": "LNJ"
    }, {
      "name": "丽江(云南丽江机场)",
      "key": "L",
      "code": "LZJ"
    }, ]
  },
  {
    title: "M",
    item: [{
      "name": "牡丹江海浪机场",
      "key": "M",
      "code": "MDG"
    }, {
      "name": "绵阳南郊机场",
      "key": "M",
      "code": "MIG"
    }, {
      "name": "芒市机场",
      "key": "M",
      "code": "LUM"
    }, {
      "name": "梅县机场",
      "key": "M",
      "code": "MXZ"
    }, ]
  },
  {
    title: "N",
    item: [{
      "name": "南京禄口机场",
      "key": "N",
      "code": "NKG"
    }, {
      "name": "宁波栎社机场",
      "key": "N",
      "code": "NGB"
    }, {
      "name": "南昌昌北机场",
      "key": "N",
      "code": "KHN"
    }, {
      "name": "南通兴东机场",
      "key": "N",
      "code": "NTG"
    }, {
      "name": "南阳姜营机场",
      "key": "N",
      "code": "NNY"
    }, {
      "name": "南充高坪机场",
      "key": "N",
      "code": "NAO"
    }, {
      "name": "那拉提机场",
      "key": "N",
      "code": "NLT"
    }, ]
  },
  {
    title: "O",
    item: [{
      "name": "鄂尔多斯伊金霍洛机场",
      "key": "O",
      "code": "DSN"
    }, ]
  },
  {
    title: "P",
    item: [{
      "name": "马公机场",
      "key": "P",
      "code": "MZG"
    }, {
      "name": "普洱(思茅)机场",
      "key": "P",
      "code": "SYM"
    }, ]
  },
  {
    title: "Q",
    item: [{
      "name": "青岛流亭机场",
      "key": "Q",
      "code": "TAO"
    }, {
      "name": "泉州晋江机场",
      "key": "Q",
      "code": "JJN"
    }, {
      "name": "秦皇岛山海关机场",
      "key": "Q",
      "code": "SHP"
    }, {
      "name": "齐齐哈尔三家子机场",
      "key": "Q",
      "code": "NDG"
    }, {
      "name": "衢州机场",
      "key": "Q",
      "code": "JUZ"
    }, {
      "name": "庆阳机场",
      "key": "Q",
      "code": "IQN"
    }, {
      "name": "且末机场",
      "key": "Q",
      "code": "IQM"
    }, {
      "name": "七美机场",
      "key": "Q",
      "code": "CMJ"
    }, ]
  },
  {
    title: "S",
    item: [{
      "name": "沈阳桃仙机场",
      "key": "S",
      "code": "SHE"
    }, {
      "name": "三亚凤凰机场",
      "key": "S",
      "code": "SYX"
    }, {
      "name": "石家庄正定机场",
      "key": "S",
      "code": "SJW"
    }, {
      "name": "苏州机场",
      "key": "S",
      "code": "SZV"
    }, {
      "name": "荆州沙市机场",
      "key": "S",
      "code": "SHS"
    }, {
      "name": "韶关机场",
      "key": "S",
      "code": "HSC"
    }, ]
  },
  {
    title: "T",
    item: [{
      "name": "台北松山机场",
      "key": "T",
      "code": "TSA"
    }, {
      "name": "天津滨海机场",
      "key": "T",
      "code": "TSN"
    }, {
      "name": "太原武宿机场",
      "key": "T",
      "code": "TYN"
    }, {
      "name": "台中清泉岗机场",
      "key": "T",
      "code": "RMQ"
    }, {
      "name": "台州路桥（原黄岩路桥）机场",
      "key": "T",
      "code": "HYN"
    }, {
      "name": "台南机场",
      "key": "T",
      "code": "TNN"
    }, {
      "name": "通辽机场",
      "key": "T",
      "code": "TGO"
    }, {
      "name": "通化机场",
      "key": "T",
      "code": "TNH"
    }, {
      "name": "台东志航机场",
      "key": "T",
      "code": "TTG"
    }, {
      "name": "铜仁凤凰机场",
      "key": "T",
      "code": "TEN"
    }, {
      "name": "塔城机场",
      "key": "T",
      "code": "TCG"
    }, {
      "name": "台中",
      "key": "T",
      "code": "TXG"
    }, {
      "name": "台东丰年机场",
      "key": "T",
      "code": "TTT"
    }, {
      "name": "桃园/桃園(原中正)机场",
      "key": "T",
      "code": "TPE"
    }, ]
  },
  {
    title: "U",
    item: [{
      "name": "乌鲁木齐地窝堡机场",
      "key": "U",
      "code": "URC"
    }, {
      "name": "乌兰浩特机场",
      "key": "U",
      "code": "HLH"
    }, ]
  },
  {
    title: "W",
    item: [{
      "name": "武汉天河机场",
      "key": "W",
      "code": "WUH"
    }, {
      "name": "温州永强机场",
      "key": "W",
      "code": "WNZ"
    }, {
      "name": "威海文登大水泊机场",
      "key": "W",
      "code": "WEH"
    }, {
      "name": "无锡硕放机场",
      "key": "W",
      "code": "WUX"
    }, {
      "name": "潍坊机场",
      "key": "W",
      "code": "WEF"
    }, {
      "name": "武夷山机场",
      "key": "W",
      "code": "WUS"
    }, {
      "name": "武汉(武汉王家墩国际机场)",
      "key": "W",
      "code": "WJD"
    }, {
      "name": "云南文山普者黑机场",
      "key": "W",
      "code": "WNH"
    }, {
      "name": "广西梧州长洲岛机场",
      "key": "W",
      "code": "WUZ"
    }, ]
  },
  {
    title: "X",
    item: [{
      "name": "厦门高崎机场",
      "key": "X",
      "code": "XMN"
    }, {
      "name": "西宁曹家堡机场",
      "key": "X",
      "code": "XNN"
    }, {
      "name": "徐州观音机场",
      "key": "X",
      "code": "XUZ"
    }, {
      "name": "襄阳刘集机场",
      "key": "X",
      "code": "XFN"
    }, {
      "name": "西昌青山机场",
      "key": "X",
      "code": "XIC"
    }, {
      "name": "锡林浩特机场",
      "key": "X",
      "code": "XIL"
    }, ]
  },
  {
    title: "Y",
    item: [{
      "name": "烟台莱山机场",
      "key": "Y",
      "code": "YNT"
    }, {
      "name": "银川河东机场",
      "key": "Y",
      "code": "INC"
    }, {
      "name": "义乌机场",
      "key": "Y",
      "code": "YIW"
    }, {
      "name": "宜昌三峡机场",
      "key": "Y",
      "code": "YIH"
    }, {
      "name": "宜宾(菜坝)机场",
      "key": "Y",
      "code": "YBP"
    }, {
      "name": "延吉朝阳川机场",
      "key": "Y",
      "code": "YNJ"
    }, {
      "name": "伊宁机场",
      "key": "Y",
      "code": "YIN"
    }, {
      "name": "江苏盐城南洋机场",
      "key": "Y",
      "code": "YNZ"
    }, {
      "name": "榆林西沙机场",
      "key": "Y",
      "code": "UYN"
    }, {
      "name": "延安二十里铺机场",
      "key": "Y",
      "code": "ENY"
    }, ]
  },
  {
    title: "Z",
    item: [{
      "name": "郑州新郑机场",
      "key": "Z",
      "code": "CGO"
    }, {
      "name": "湛江机场",
      "key": "Z",
      "code": "ZHA"
    }, {
      "name": "珠海三灶机场",
      "key": "Z",
      "code": "ZUH"
    }, {
      "name": "张家界荷花机场",
      "key": "Z",
      "code": "DYG"
    }, {
      "name": "遵义机场",
      "key": "Z",
      "code": "ZYI"
    }, {
      "name": "舟山普陀山朱家尖机场",
      "key": "Z",
      "code": "HSN"
    }, {
      "name": "昭通机场",
      "key": "Z",
      "code": "ZAT"
    }, ]
  },
]

module.exports = city;