var city={
  "error_code": 0,
    "reason": "成功",
      "result": [{
        "CabinDesc": null,
        "CabinType": "W",
        "basicCabinType": "Y",
        "MoneyType": "CNY",
        "FarePrice": null,
        "SinglePrice": "730.00",
        "RoundPrice": "730.00",
        "PolicyCode": null,
        "discountRate": "100",
        "startDate": "2016-03-27",
        "endDate": "2020-01-24",
        "airline": "CZ",
        "AirportTax": "50",
        "fuelTax": "0",
        "rule": "CZ25  PFN:01",
        "Points": null,
        "TradePrice": null,
        "ChdPrice": null,
        "orgCity": "NNG",
        "dstcity": "CAN"
      },
      {
        "CabinDesc": null,
        "CabinType": "Y",
        "basicCabinType": "Y",
        "MoneyType": "CNY",
        "FarePrice": null,
        "SinglePrice": "730.00",
        "RoundPrice": "730.00",
        "PolicyCode": null,
        "discountRate": "100",
        "startDate": "2016-03-27",
        "endDate": "2020-01-24",
        "airline": "CZ",
        "AirportTax": "50",
        "fuelTax": "0",
        "rule": "CZ25  PFN:02",
        "Points": null,
        "TradePrice": null,
        "ChdPrice": null,
        "orgCity": "NNG",
        "dstcity": "CAN"
      },
      {
        "CabinDesc": null,
        "CabinType": "F",
        "basicCabinType": "F",
        "MoneyType": "CNY",
        "FarePrice": null,
        "SinglePrice": "2040.00",
        "RoundPrice": "0.00",
        "PolicyCode": null,
        "discountRate": "279",
        "startDate": "2016-03-27",
        "endDate": "2020-01-24",
        "airline": "ZH",
        "AirportTax": "50",
        "fuelTax": "0",
        "rule": "H002  PFN:03",
        "Points": null,
        "TradePrice": null,
        "ChdPrice": null,
        "orgCity": "NNG",
        "dstcity": "CAN"
      },
      {
        "CabinDesc": null,
        "CabinType": "C",
        "basicCabinType": "C",
        "MoneyType": "CNY",
        "FarePrice": null,
        "SinglePrice": "1970.00",
        "RoundPrice": "0.00",
        "PolicyCode": null,
        "discountRate": "270",
        "startDate": "2017-06-15",
        "endDate": "2020-01-24",
        "airline": "ZH",
        "AirportTax": "50",
        "fuelTax": "0",
        "rule": "L002  PFN:04",
        "Points": null,
        "TradePrice": null,
        "ChdPrice": null,
        "orgCity": "NNG",
        "dstcity": "CAN"
      },
      {
        "CabinDesc": null,
        "CabinType": "F",
        "basicCabinType": "F",
        "MoneyType": "CNY",
        "FarePrice": null,
        "SinglePrice": "0.00",
        "RoundPrice": "3940.00",
        "PolicyCode": null,
        "discountRate": "0",
        "startDate": "2016-03-27",
        "endDate": "2020-01-24",
        "airline": "ZH",
        "AirportTax": "50",
        "fuelTax": "0",
        "rule": "H002  PFN:05",
        "Points": null,
        "TradePrice": null,
        "ChdPrice": null,
        "orgCity": "NNG",
        "dstcity": "CAN"
      },
      {
        "CabinDesc": null,
        "CabinType": "C",
        "basicCabinType": "C",
        "MoneyType": "CNY",
        "FarePrice": null,
        "SinglePrice": "0.00",
        "RoundPrice": "3800.00",
        "PolicyCode": null,
        "discountRate": "0",
        "startDate": "2017-06-15",
        "endDate": "2020-01-24",
        "airline": "ZH",
        "AirportTax": "50",
        "fuelTax": "0",
        "rule": "L002  PFN:06",
        "Points": null,
        "TradePrice": null,
        "ChdPrice": null,
        "orgCity": "NNG",
        "dstcity": "CAN"
      },
      {
        "CabinDesc": null,
        "CabinType": "G",
        "basicCabinType": "Y",
        "MoneyType": "CNY",
        "FarePrice": null,
        "SinglePrice": "730.00",
        "RoundPrice": "1460.00",
        "PolicyCode": null,
        "discountRate": "100",
        "startDate": "2018-03-05",
        "endDate": "2020-01-24",
        "airline": "ZH",
        "AirportTax": "50",
        "fuelTax": "0",
        "rule": "M002  PFN:07",
        "Points": null,
        "TradePrice": null,
        "ChdPrice": null,
        "orgCity": "NNG",
        "dstcity": "CAN"
      },
      {
        "CabinDesc": null,
        "CabinType": "Y",
        "basicCabinType": "Y",
        "MoneyType": "CNY",
        "FarePrice": null,
        "SinglePrice": "730.00",
        "RoundPrice": "1460.00",
        "PolicyCode": null,
        "discountRate": "100",
        "startDate": "2018-03-05",
        "endDate": "2020-01-24",
        "airline": "ZH",
        "AirportTax": "50",
        "fuelTax": "0",
        "rule": "H002  PFN:08",
        "Points": null,
        "TradePrice": null,
        "ChdPrice": null,
        "orgCity": "NNG",
        "dstcity": "CAN"
      },
      {
        "CabinDesc": null,
        "CabinType": "B",
        "basicCabinType": "Y",
        "MoneyType": "CNY",
        "FarePrice": null,
        "SinglePrice": "720.00",
        "RoundPrice": "1440.00",
        "PolicyCode": null,
        "discountRate": "99",
        "startDate": "2018-03-05",
        "endDate": "2020-01-24",
        "airline": "ZH",
        "AirportTax": "50",
        "fuelTax": "0",
        "rule": "H000  PFN:09",
        "Points": null,
        "TradePrice": null,
        "ChdPrice": null,
        "orgCity": "NNG",
        "dstcity": "CAN"
      },
      {
        "CabinDesc": null,
        "CabinType": "M",
        "basicCabinType": "Y",
        "MoneyType": "CNY",
        "FarePrice": null,
        "SinglePrice": "660.00",
        "RoundPrice": "1320.00",
        "PolicyCode": null,
        "discountRate": "90",
        "startDate": "2018-03-05",
        "endDate": "2020-01-24",
        "airline": "ZH",
        "AirportTax": "50",
        "fuelTax": "0",
        "rule": "H000  PFN:10",
        "Points": null,
        "TradePrice": null,
        "ChdPrice": null,
        "orgCity": "NNG",
        "dstcity": "CAN"
      },
      {
        "CabinDesc": null,
        "CabinType": "M1",
        "basicCabinType": "Y",
        "MoneyType": "CNY",
        "FarePrice": null,
        "SinglePrice": "630.00",
        "RoundPrice": "1260.00",
        "PolicyCode": null,
        "discountRate": "86",
        "startDate": "2018-03-05",
        "endDate": "2020-01-24",
        "airline": "ZH",
        "AirportTax": "50",
        "fuelTax": "0",
        "rule": "H000  PFN:11",
        "Points": null,
        "TradePrice": null,
        "ChdPrice": null,
        "orgCity": "NNG",
        "dstcity": "CAN"
      },
      {
        "CabinDesc": null,
        "CabinType": "U",
        "basicCabinType": "Y",
        "MoneyType": "CNY",
        "FarePrice": null,
        "SinglePrice": "590.00",
        "RoundPrice": "1180.00",
        "PolicyCode": null,
        "discountRate": "81",
        "startDate": "2018-03-05",
        "endDate": "2020-01-24",
        "airline": "ZH",
        "AirportTax": "50",
        "fuelTax": "0",
        "rule": "H000  PFN:12",
        "Points": null,
        "TradePrice": null,
        "ChdPrice": null,
        "orgCity": "NNG",
        "dstcity": "CAN"
      },
      {
        "CabinDesc": null,
        "CabinType": "H",
        "basicCabinType": "Y",
        "MoneyType": "CNY",
        "FarePrice": null,
        "SinglePrice": "550.00",
        "RoundPrice": "1100.00",
        "PolicyCode": null,
        "discountRate": "75",
        "startDate": "2016-08-01",
        "endDate": "2020-01-24",
        "airline": "ZH",
        "AirportTax": "50",
        "fuelTax": "0",
        "rule": "H000  PFN:13",
        "Points": null,
        "TradePrice": null,
        "ChdPrice": null,
        "orgCity": "NNG",
        "dstcity": "CAN"
      },
      {
        "CabinDesc": null,
        "CabinType": "Q",
        "basicCabinType": "Y",
        "MoneyType": "CNY",
        "FarePrice": null,
        "SinglePrice": "520.00",
        "RoundPrice": "1040.00",
        "PolicyCode": null,
        "discountRate": "71",
        "startDate": "2016-08-01",
        "endDate": "2020-01-24",
        "airline": "ZH",
        "AirportTax": "50",
        "fuelTax": "0",
        "rule": "H000  PFN:14",
        "Points": null,
        "TradePrice": null,
        "ChdPrice": null,
        "orgCity": "NNG",
        "dstcity": "CAN"
      },
      {
        "CabinDesc": null,
        "CabinType": "Q1",
        "basicCabinType": "Y",
        "MoneyType": "CNY",
        "FarePrice": null,
        "SinglePrice": "480.00",
        "RoundPrice": "960.00",
        "PolicyCode": null,
        "discountRate": "66",
        "startDate": "2016-08-01",
        "endDate": "2020-01-24",
        "airline": "ZH",
        "AirportTax": "50",
        "fuelTax": "0",
        "rule": "H000  PFN:15",
        "Points": null,
        "TradePrice": null,
        "ChdPrice": null,
        "orgCity": "NNG",
        "dstcity": "CAN"
      },
      {
        "CabinDesc": null,
        "CabinType": "V",
        "basicCabinType": "Y",
        "MoneyType": "CNY",
        "FarePrice": null,
        "SinglePrice": "450.00",
        "RoundPrice": "900.00",
        "PolicyCode": null,
        "discountRate": "62",
        "startDate": "2016-08-01",
        "endDate": "2020-01-24",
        "airline": "ZH",
        "AirportTax": "50",
        "fuelTax": "0",
        "rule": "H000  PFN:16",
        "Points": null,
        "TradePrice": null,
        "ChdPrice": null,
        "orgCity": "NNG",
        "dstcity": "CAN"
      },
      {
        "CabinDesc": null,
        "CabinType": "V1",
        "basicCabinType": "Y",
        "MoneyType": "CNY",
        "FarePrice": null,
        "SinglePrice": "410.00",
        "RoundPrice": "820.00",
        "PolicyCode": null,
        "discountRate": "56",
        "startDate": "2016-08-01",
        "endDate": "2020-01-24",
        "airline": "ZH",
        "AirportTax": "50",
        "fuelTax": "0",
        "rule": "H000  PFN:17",
        "Points": null,
        "TradePrice": null,
        "ChdPrice": null,
        "orgCity": "NNG",
        "dstcity": "CAN"
      },
      {
        "CabinDesc": null,
        "CabinType": "W",
        "basicCabinType": "Y",
        "MoneyType": "CNY",
        "FarePrice": null,
        "SinglePrice": "370.00",
        "RoundPrice": "740.00",
        "PolicyCode": null,
        "discountRate": "51",
        "startDate": "2016-08-01",
        "endDate": "2020-01-24",
        "airline": "ZH",
        "AirportTax": "50",
        "fuelTax": "0",
        "rule": "H000  PFN:18",
        "Points": null,
        "TradePrice": null,
        "ChdPrice": null,
        "orgCity": "NNG",
        "dstcity": "CAN"
      },
      {
        "CabinDesc": null,
        "CabinType": "S",
        "basicCabinType": "Y",
        "MoneyType": "CNY",
        "FarePrice": null,
        "SinglePrice": "330.00",
        "RoundPrice": "660.00",
        "PolicyCode": null,
        "discountRate": "45",
        "startDate": "2016-03-27",
        "endDate": "2020-01-24",
        "airline": "ZH",
        "AirportTax": "50",
        "fuelTax": "0",
        "rule": "H000  PFN:19",
        "Points": null,
        "TradePrice": null,
        "ChdPrice": null,
        "orgCity": "NNG",
        "dstcity": "CAN"
      },
      {
        "CabinDesc": null,
        "CabinType": "E",
        "basicCabinType": "Y",
        "MoneyType": "CNY",
        "FarePrice": null,
        "SinglePrice": "290.00",
        "RoundPrice": "580.00",
        "PolicyCode": null,
        "discountRate": "40",
        "startDate": "2016-03-27",
        "endDate": "2020-01-24",
        "airline": "ZH",
        "AirportTax": "50",
        "fuelTax": "0",
        "rule": "H000  PFN:20",
        "Points": null,
        "TradePrice": null,
        "ChdPrice": null,
        "orgCity": "NNG",
        "dstcity": "CAN"
      }]
}

module.exports = city;