var city = [{
    title: "热门",
    item: [{
      "name": "北京",
      "key": "热门",
      "priceA": "300",
      "priceB": "250",
    }, {
      "name": "深圳",
      "key": "热门",
      "priceA": "300",
      "priceB": "250",
    }, {
      "name": "广州",
      "key": "热门",
      "priceA": "300",
      "priceB": "250",
    }, {
      "name": "上海",
      "key": "热门",
      "priceA": "300",
      "priceB": "250",
    }, {
      "name": "杭州",
      "key": "热门",
      "priceA": "250",
      "priceB": "200",
    }, {
      "name": "南宁",
      "key": "热门",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "长沙",
      "key": "热门",
      "priceA": "200",
      "priceB": "150",
    }, ]
  },
  {
    title: "A",
    item: [{
      "name": "鞍山",
      "key": "A",
      "priceA": "150",
      "priceB": "120",
    }, ]
  },
  {
    title: "B",
    item: [{
      "name": "包头",
      "key": "B",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "蚌埠",
      "key": "B",
      "priceA": "150",
      "priceB": "120",
    }, {
      "name": "保定",
      "key": "B",
      "priceA": "150",
      "priceB": "120",
    }, ]
  },
  {
    title: "C",
    item: [{
      "name": "潮州",
      "key": "C",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "长春",
      "key": "C",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "常州",
      "key": "C",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "成都",
      "key": "C",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "滁州",
      "key": "C",
      "priceA": "150",
      "priceB": "120",
    }, {
      "name": "沧州",
      "key": "C",
      "priceA": "150",
      "priceB": "120",
    }, {
      "name": "常德",
      "key": "C",
      "priceA": "150",
      "priceB": "120",
    }, ]
  },
  {
    title: "D",
    item: [{
      "name": "东莞",
      "key": "D",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "大庆",
      "key": "D",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "大连",
      "key": "D",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "德阳",
      "key": "D",
      "priceA": "150",
      "priceB": "120",
    }, ]
  },
  {
    title: "F",
    item: [{
      "name": "福州",
      "key": "F",
      "priceA": "250",
      "priceB": "200",
    }, {
      "name": "佛山",
      "key": "F",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "阜阳",
      "key": "F",
      "priceA": "150",
      "priceB": "120",
    }, ]
  },
  {
    title: "G",
    item: [{
      "name": "桂林",
      "key": "G",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "贵阳",
      "key": "G",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "赣州",
      "key": "G",
      "priceA": "150",
      "priceB": "120",
    }, ]
  },
  {
    title: "H",
    item: [{
      "name": "合肥",
      "key": "H",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "惠州",
      "key": "H",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "海口",
      "key": "H",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "哈尔滨",
      "key": "H",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "淮安",
      "key": "H",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "呼和浩特",
      "key": "H",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "菏泽",
      "key": "H",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "湖州",
      "key": "H",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "邯郸",
      "key": "H",
      "priceA": "150",
      "priceB": "120",
    }, {
      "name": "黄冈",
      "key": "H",
      "priceA": "150",
      "priceB": "120",
    }, {
      "name": "衡阳",
      "key": "H",
      "priceA": "150",
      "priceB": "120",
    }, ]
  },
  {
    title: "J",
    item: [{
      "name": "济南",
      "key": "J",
      "priceA": "250",
      "priceB": "200",
    }, {
      "name": "江门",
      "key": "J",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "揭阳",
      "key": "J",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "济宁",
      "key": "J",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "金华",
      "key": "J",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "嘉兴",
      "key": "J",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "荆州",
      "key": "J",
      "priceA": "150",
      "priceB": "120",
    }, {
      "name": "吉林",
      "key": "J",
      "priceA": "150",
      "priceB": "120",
    }, {
      "name": "九江",
      "key": "J",
      "priceA": "150",
      "priceB": "120",
    }, ]
  },
  {
    title: "K",
    item: [{
      "name": "昆明",
      "key": "K",
      "priceA": "250",
      "priceB": "200",
    }, ]
  },
  {
    title: "L",
    item: [{
      "name": "兰州",
      "key": "L",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "洛阳",
      "key": "L",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "连云港",
      "key": "L",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "临沂",
      "key": "L",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "柳州",
      "key": "L",
      "priceA": "150",
      "priceB": "120",
    }, {
      "name": "廊坊",
      "key": "L",
      "priceA": "150",
      "priceB": "120",
    }, ]
  },
  {
    title: "M",
    item: [{
      "name": "绵阳",
      "key": "M",
      "priceA": "150",
      "priceB": "120",
    }, ]
  },
  {
    title: "N",
    item: [{
      "name": "南京",
      "key": "N",
      "priceA": "250",
      "priceB": "200",
    }, {
      "name": "宁德",
      "key": "N",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "南阳",
      "key": "N",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "南通",
      "key": "N",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "南昌",
      "key": "N",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "宁波",
      "key": "N",
      "priceA": "200",
      "priceB": "150",
    }, ]
  },
  {
    title: "P",
    item: [{
      "name": "莆田",
      "key": "P",
      "priceA": "200",
      "priceB": "150",
    }, ]
  },
  {
    title: "Q",
    item: [{
      "name": "青岛",
      "key": "Q",
      "priceA": "250",
      "priceB": "200",
    }, {
      "name": "泉州",
      "key": "Q",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "曲靖",
      "key": "Q",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "秦皇岛",
      "key": "Q",
      "priceA": "150",
      "priceB": "120",
    }, ]
  },
  {
    title: "S",
    item: [{
      "name": "汕头",
      "key": "S",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "石家庄",
      "key": "S",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "商丘",
      "key": "S",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "苏州",
      "key": "S",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "宿迁",
      "key": "S",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "沈阳",
      "key": "S",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "绍兴",
      "key": "S",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "三亚",
      "key": "S",
      "priceA": "150",
      "priceB": "120",
    }, {
      "name": "上饶",
      "key": "S",
      "priceA": "150",
      "priceB": "120",
    }, ]
  },
  {
    title: "T",
    item: [{
      "name": "天津",
      "key": "T",
      "priceA": "250",
      "priceB": "200",
    }, {
      "name": "泰州",
      "key": "T",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "太原",
      "key": "T",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "台州",
      "key": "T",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "铜陵",
      "key": "T",
      "priceA": "150",
      "priceB": "120",
    }, {
      "name": "唐山",
      "key": "T",
      "priceA": "150",
      "priceB": "120",
    }, ]
  },
  {
    title: "W",
    item: [{
      "name": "武汉",
      "key": "W",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "无锡",
      "key": "W",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "潍坊",
      "key": "W",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "威海",
      "key": "W",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "乌鲁木齐",
      "key": "W",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "温州",
      "key": "W",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "芜湖",
      "key": "W",
      "priceA": "150",
      "priceB": "120",
    }, ]
  },
  {
    title: "X",
    item: [{
      "name": "厦门",
      "key": "X",
      "priceA": "250",
      "priceB": "200",
    }, {
      "name": "信阳",
      "key": "X",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "许昌",
      "key": "X",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "新乡",
      "key": "X",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "徐州",
      "key": "X",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "西宁",
      "key": "X",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "西安",
      "key": "X",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "邢台",
      "key": "X",
      "priceA": "150",
      "priceB": "120",
    }, {
      "name": "襄阳",
      "key": "X",
      "priceA": "150",
      "priceB": "120",
    }, {
      "name": "湘潭",
      "key": "X",
      "priceA": "150",
      "priceB": "120",
    }, {
      "name": "咸阳",
      "key": "X",
      "priceA": "150",
      "priceB": "120",
    }, ]
  },
  {
    title: "Y",
    item: [{
      "name": "扬州",
      "key": "Y",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "盐城",
      "key": "Y",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "银川",
      "key": "Y",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "烟台",
      "key": "Y",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "宜昌",
      "key": "Y",
      "priceA": "150",
      "priceB": "120",
    }, {
      "name": "岳阳",
      "key": "Y",
      "priceA": "150",
      "priceB": "120",
    }, {
      "name": "宜春",
      "key": "Y",
      "priceA": "150",
      "priceB": "120",
    }, ]
  },
  {
    title: "Z",
    item: [{
      "name": "郑州",
      "key": "Z",
      "priceA": "250",
      "priceB": "200",
    }, {
      "name": "漳州",
      "key": "Z",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "中山",
      "key": "Z",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "珠海",
      "key": "Z",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "湛江",
      "key": "Z",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "肇庆",
      "key": "Z",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "驻马店",
      "key": "Z",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "镇江",
      "key": "Z",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "淄博",
      "key": "Z",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "重庆",
      "key": "Z",
      "priceA": "200",
      "priceB": "150",
    }, {
      "name": "遵义",
      "key": "Z",
      "priceA": "150",
      "priceB": "120",
    }, {
      "name": "株洲",
      "key": "Z",
      "priceA": "150",
      "priceB": "120",
    }, ]
  },

]

module.exports = city;